# Generated by Django 4.1 on 2023-02-21 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="erole",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 2, 21, 15, 34, 5, 484817, tzinfo=datetime.timezone.utc
                ),
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
